import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase credentials in .env.local')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
})

async function addIoTTopics() {
  console.log('Adding Internet of Things (IoT) topics...\n')

  try {
    // Get Cybersecurity subject ID
    const { data: subject, error: subjectError } = await supabase
      .from('subjects')
      .select('id')
      .eq('name', 'Cybersecurity')
      .single()

    if (subjectError || !subject) {
      console.error('❌ Error finding Cybersecurity subject:', subjectError)
      return
    }

    const subjectId = subject.id

    // Add Internet of Things (IoT) (Level 1)
    const { data: iot, error: iotError } = await supabase
      .from('topics')
      .insert({
        subject_id: subjectId,
        parent_topic_id: null,
        name: 'Internet of Things (IoT)',
        description: 'Devices that can report state and configuration data and be remotely managed over IP networks. The Internet of Things (IoT) refers to the network of physical devices, vehicles, appliances, and other objects embedded with sensors, software, and connectivity, enabling them to collect and exchange data. Sensors are small devices designed to detect changes in the physical environment, such as temperature, humidity, and motion. On the other hand, actuators can perform actions based on data collected by sensors, such as turning on a light or adjusting a thermostat. IoT devices communicate with each other and with other (often public cloud-based) systems over the Internet to exchange data and receive instructions. Cloud-based systems form an essential component of IoT infrastructures as they provide the computational power needed to perform data analytics on the large amounts of data generated by IoT devices.',
        hierarchy_level: 1
      })
      .select()
      .single()

    if (iotError) {
      console.error('❌ Error creating IoT topic:', iotError)
      return
    }

    console.log('✅ Created: Internet of Things (IoT) (Level 1)')

    // Add Level 2 subtopics
    const level2Topics = [
      {
        name: 'IoT Examples',
        description: 'There are many IoT devices and applications in use today. For example, smart homes often use IoT sensors and actuators to control lighting, temperature, and security systems, allowing homeowners to monitor and adjust their homes remotely. Smart cities also use IoT to manage traffic, monitor air quality, and improve public safety. In the healthcare industry, IoT devices such as wearables and implantable devices can collect data on patient health and send it to healthcare providers for analysis. In agriculture, IoT sensors are used to monitor soil conditions, weather patterns, and crop growth, helping farmers make more informed decisions about planting and harvesting. IoT devices are used to improve efficiency, convenience, and quality of life in a wide range of industries and applications.'
      },
      {
        name: 'Factors Driving Adoption of IoT',
        description: 'Several factors drive the rapid adoption of IoT. The significantly decreased cost of IoT sensors and devices over the past few years has made them more affordable and accessible to businesses and consumers. This has enabled the development of a wide range of IoT applications and services that were previously too expensive to implement. Advances in connectivity technology, such as 5G and low-power wireless networks, have made connecting and managing large numbers of IoT devices easier and more efficient. This has also improved the speed and reliability of data transmission, enabling real-time monitoring and response. The proverbial explosion of data generated by IoT devices has led to new data analytics tools and techniques, such as machine learning and artificial intelligence, that help organizations analyze vast amounts of data and extract valuable insights. The COVID-19 pandemic has accelerated the adoption of IoT in many industries, particularly in healthcare, where remote monitoring and telemedicine have become increasingly important. As more organizations recognize the value of IoT, adoption is likely to continue to grow in the coming years.'
      },
      {
        name: 'Security Risks Associated with IoT',
        description: 'There are several significant security risks associated with IoT. One major risk is the large number of IoT devices deployed without adequate security measures. Many IoT devices are designed with limited processing power and memory, making it difficult to implement strong security controls. This can make them vulnerable to cyberattacks, compromising data privacy, system integrity, and physical safety. Another risk is the need for more standardization in IoT devices and protocols. Compatibility issues can make integrating different IoT devices and services difficult. It can also make implementing security controls more difficult, as different devices may have different security requirements and protocols, making them incompatible. The sheer volume of data generated by IoT devices can make securing and protecting sensitive information difficult. As more devices are connected to the Internet, there is an increasing risk of data breaches and cyberattacks, which can result in the theft of personal and sensitive data. Examples of security issues caused by implementing or using IoT include the Mirai botnet attack, which infected millions of IoT devices and used them to launch massive distributed denial of service (DDoS) attacks on websites and online services. In another case, a casino was hacked through a smart thermometer in a fish tank, which was used as a backdoor to access the casino\'s network. There have also been cases of IoT devices being hacked to spy on individuals, such as baby monitors and home security cameras. IoT devices often have poor security characteristics for several reasons. IoT devices are typically designed to focus on functionality rather than security and have limited processing power and memory, making it difficult to implement strong security controls. Many IoT devices must be low cost, making it challenging for manufacturers to prioritize security features in their design and development process. Many IoT devices are rushed to market without proper security testing, resulting in vulnerabilities that cybercriminals can exploit. Additionally, consumers and organizations need more awareness of the security risks associated with IoT devices. Many users and organizations do not realize that their devices are vulnerable to cyberattacks and may not take the necessary steps to protect themselves, such as changing default passwords or updating firmware.'
      },
      {
        name: 'Best Practice Guidance for IoT',
        description: 'Organizations providing IoT security best practices and standards: The Internet of Things Security Foundation (IoTSF) - https://iotsecurityfoundation.org | Industrial Internet Consortium (IIC) Security Framework - https://www.iiconsortium.org/iisf/ | Cloud Security Alliance (CSA) IoT Security Controls Framework - https://cloudsecurityalliance.org/artifacts/iot-security-controls-framework | European Telecommunications Standards Institute (ETSI) IoT Security Standards - https://www.etsi.org/technologies/consumer-iot-security'
      }
    ]

    for (const topic of level2Topics) {
      const { error } = await supabase
        .from('topics')
        .insert({
          subject_id: subjectId,
          parent_topic_id: iot.id,
          name: topic.name,
          description: topic.description,
          hierarchy_level: 2
        })

      if (error) {
        console.error(`❌ Error creating "${topic.name}":`, error)
      } else {
        console.log(`✅ Created: ${topic.name} (Level 2)`)
      }
    }

    console.log('\n✨ Done! Added 5 new topics (1 Level 1, 4 Level 2)')

  } catch (error) {
    console.error('❌ Error:', error)
  }
}

addIoTTopics().catch(console.error)
