-- Migration: Add comprehensive Identity and Access Management topics
-- Converts Authentication, Authorization, and IAM from standalone roots to trunks with subtopics
-- Adds Federation as new Level 1 trunk
-- Total: ~90 new topics organized into 4-level hierarchy

DO $$
DECLARE
  v_subject_id UUID;
  v_auth_id UUID;
  v_authz_id UUID;
  v_iam_id UUID;
  v_federation_id UUID;

  -- Authentication Level 2
  v_auth_methods_id UUID;
  v_auth_protocols_id UUID;
  v_auth_design_id UUID;
  v_auth_factor_id UUID;
  v_password_practices_id UUID;

  -- Authentication Level 3
  v_biometric_id UUID;
  v_token_gen_id UUID;
  v_kerberos_id UUID;

  -- Authorization Level 2
  v_access_control_id UUID;

  -- IAM Level 2
  v_account_mgmt_id UUID;
  v_account_lifecycle_id UUID;
  v_account_restrictions_id UUID;

  -- IAM Level 3
  v_provisioning_id UUID;
  v_zsp_id UUID;
BEGIN
  -- Get the subject ID
  SELECT id INTO v_subject_id FROM subjects WHERE name = 'Cybersecurity' LIMIT 1;

  -- Get existing Authentication, Authorization, and IAM IDs
  SELECT id INTO v_auth_id FROM topics WHERE name = 'Authentication' AND hierarchy_level = 1;
  SELECT id INTO v_authz_id FROM topics WHERE name = 'Authorization' AND hierarchy_level = 1;
  SELECT id INTO v_iam_id FROM topics WHERE name = 'Identity and Access Management (IAM)' AND hierarchy_level = 1;

  -- Update descriptions for existing Level 1 topics
  UPDATE topics SET description = 'The process of determining that a user or system is who or what it declares itself to be, typically using credentials such as passwords, biometrics, tokens, or certificates.' WHERE id = v_auth_id;
  UPDATE topics SET description = 'The process of determining what rights and privileges a particular entity has, based on an access control model and policy rules.' WHERE id = v_authz_id;
  UPDATE topics SET description = 'Security processes that provide identification, authentication, and authorization mechanisms for users, computers, and other entities to work with organizational assets.' WHERE id = v_iam_id;

  -----------------------------------------------------------------------------
  -- AUTHENTICATION BRANCH
  -----------------------------------------------------------------------------

  -- Level 2: Authentication Methods
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_id, 'Authentication Methods',
    'Technologies and techniques used to verify the identity of users, including knowledge-based, ownership-based, and biometric factors.', 2)
  RETURNING id INTO v_auth_methods_id;

  -- Level 3: Authentication Method Types (under Authentication Methods)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_auth_methods_id, 'Personal Identification Number (PIN)',
      'A number used in conjunction with authentication devices such as smart cards; as the PIN should be known only to the user, loss of the smart card should not represent a security risk.', 3),
    (v_subject_id, v_auth_methods_id, 'Password Manager',
      'Software that can suggest and store site and app passwords to reduce risks from poor user choices and behavior. Most browsers have a built-in password manager.', 3),
    (v_subject_id, v_auth_methods_id, 'Multifactor Authentication (MFA)',
      'An authentication scheme that requires the user to present at least two different factors as credentials; for example, something you know, something you have, something you are, something you do, and somewhere you are. Specifying two factors is known as "2FA."', 3),
    (v_subject_id, v_auth_methods_id, 'Soft Authentication Token',
      'OTP sent to a registered number or email account or generated by an authenticator app as a means of two-step verification when authenticating account access.', 3),
    (v_subject_id, v_auth_methods_id, 'Hard authentication token',
      'Authentication token generated by a cryptoprocessor on a dedicated hardware device. As the token is never transmitted directly, this implements an ownership factor within a multifactor authentication scheme.', 3),
    (v_subject_id, v_auth_methods_id, 'Smart Cards',
      'A security device similar to a credit card that can store authentication information, such as a user''s private key, on an embedded cryptoprocessor.', 3),
    (v_subject_id, v_auth_methods_id, 'One-time password (OTP)',
      'A password that is generated for use in one specific session and becomes invalid after the session ends.', 3),
    (v_subject_id, v_auth_methods_id, 'Security Key',
      'Portable HSM with a computer interface, such as USB or NFC, used for multifactor authentication.', 3),
    (v_subject_id, v_auth_methods_id, 'Passwordless',
      'Multifactor authentication scheme that uses ownership and biometric factors, but not knowledge factors.', 3),
    (v_subject_id, v_auth_methods_id, 'Attestation',
      'Capability of an authenticator or other cryptographic module to prove that it is a root of trust and can provide reliable reporting to prove that a device or computer is a trustworthy platform.', 3);

  -- Level 3: Biometric Authentication (branch under Authentication Methods)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_methods_id, 'Biometric Authentication',
    'An authentication mechanism that allows a user to perform a biometric scan to operate an entry or access system. Physical characteristics stored as a digital data template can be used to authenticate a user. Typical features used include facial pattern, iris, retina, fingerprint pattern, and signature recognition.', 3)
  RETURNING id INTO v_biometric_id;

  -- Level 4: Biometric metrics (under Biometric Authentication)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_biometric_id, 'False Rejection Rate (FRR)',
      'A biometric assessment metric that measures the number of valid subjects who are denied access.', 4),
    (v_subject_id, v_biometric_id, 'False Acceptance Rate (FAR)',
      'A biometric assessment metric that measures the number of unauthorized users who are mistakenly allowed access.', 4),
    (v_subject_id, v_biometric_id, 'Crossover Error Rate (CER)',
      'A biometric evaluation factor expressing the point at which FAR and FRR meet, with a low value indicating better performance.', 4),
    (v_subject_id, v_biometric_id, 'Throughput (Speed)',
      'The time required to create a template for each user and the time required to authenticate. This is a major consideration for high-traffic access points, such as airports or railway stations.', 4),
    (v_subject_id, v_biometric_id, 'Failure to Enroll Rate (FER)',
      'Incidents in which a template cannot be created and matched for a user during enrollment.', 4),
    (v_subject_id, v_biometric_id, 'Cost/Implementation',
      'Some scanner types are more expensive, whereas others are not easy to incorporate on mobile devices.', 4);

  -- Level 3: Token Generation (branch under Authentication Methods)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_methods_id, 'Token Generation',
    'Methods for generating cryptographic tokens for authentication, including certificate-based, OTP-based, and public/private key approaches.', 3)
  RETURNING id INTO v_token_gen_id;

  -- Level 4: Token Generation methods (under Token Generation)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_token_gen_id, 'Certificate-Based Authentication',
      'The supplicant controls a private key that can generate a unique signed token. The identity provider can verify the signature via the public key. The main drawback of this approach is the administrative burden of implementing PKI to issue digital certificates.', 4),
    (v_subject_id, v_token_gen_id, 'Fast Identity Online (FIDO) Universal 2nd Factor (U2F)',
      'Uses a public/private key pair to register each account, avoiding the need to communicate a shared secret, which is a weakness of HOTP and TOTP. The private key is locked to the U2F device and signs the token; the public key is registered with the authentication server and verifies the token.', 4);

  -- Level 2: Authentication Protocols
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_id, 'Authentication Protocols',
    'Standards and systems for performing authentication across networks and platforms, including local, network, and remote authentication mechanisms.', 2)
  RETURNING id INTO v_auth_protocols_id;

  -- Level 3: Authentication Protocol Types (under Authentication Protocols)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_auth_protocols_id, 'Local Authentication',
      'Windows local sign-in is the Local Security Authority Subsystem Service (LSASS) that compares the submitted credential to a hash stored in the Security Accounts Manager (SAM) database, which is part of the registry. This is also referred to as interactive logon.', 3),
    (v_subject_id, v_auth_protocols_id, 'Network Authentication',
      'Windows network sign-in is LSASS which can pass the credentials for authentication to an Active Directory (AD) domain controller. The preferred system for network authentication is based on Kerberos, but legacy network applications might use NT LAN Manager (NTLM) authentication.', 3),
    (v_subject_id, v_auth_protocols_id, 'Remote Authentication',
      'Remote sign-in is used if the user''s device is not directly connected to the local network, authentication can take place over a virtual private network (VPN), enterprise Wi-Fi, or web portal. These use protocols to create a secure connection between the client machine, the remote access device, and the authentication server.', 3),
    (v_subject_id, v_auth_protocols_id, 'Linux Authentication',
      'In Linux, local user account names are stored in /etc/passwd. When a user logs in to a local interactive shell, the password is checked against a hash stored in /etc/shadow. Interactive login over a network is typically accomplished using Secure Shell (SSH). With SSH, the user can be authenticated using cryptographic keys instead of a password.', 3),
    (v_subject_id, v_auth_protocols_id, 'Pluggable Authentication Module (PAM)',
      'A framework for implementing authentication providers in Linux.', 3),
    (v_subject_id, v_auth_protocols_id, 'NT LAN Manager (NTLM) Authentication',
      'A challenge-response authentication protocol created by Microsoft for use in its products.', 3),
    (v_subject_id, v_auth_protocols_id, 'Directory Service',
      'A network service that stores identity information about all the objects in a particular network, including users, groups, servers, client computers, and printers.', 3),
    (v_subject_id, v_auth_protocols_id, 'Lightweight Directory Access Protocol (LDAP)',
      'Protocol used to access network directory databases, which store information about authorized users and their privileges, as well as other organizational information.', 3),
    (v_subject_id, v_auth_protocols_id, 'Distinguished Name (DN)',
      'A collection of attributes that define a unique identifier for any given resource within an X.500-like directory.', 3),
    (v_subject_id, v_auth_protocols_id, 'Single Sign-on (SSO)',
      'Authentication technology that enables a user to authenticate once and receive authorizations for multiple services.', 3);

  -- Level 3: Kerberos (branch under Authentication Protocols)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_protocols_id, 'Kerberos',
    'A single sign-on authentication and authorization service that is based on a time-sensitive, ticket-granting system.', 3)
  RETURNING id INTO v_kerberos_id;

  -- Level 4: Kerberos components (under Kerberos)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_kerberos_id, 'Key Distribution Center (KDC)',
      'A component of Kerberos that authenticates users and issues tickets (tokens).', 4),
    (v_subject_id, v_kerberos_id, 'Ticket Granting Ticket (TGT)',
      'In Kerberos, a token issued to an authenticated account to allow access to authorized application servers.', 4),
    (v_subject_id, v_kerberos_id, 'TGS session Key',
      'It communicates between the client and the Ticket Granting Service (TGS). This is encrypted using a hash of the user''s password.', 4);

  -- Level 2: Authentication Design
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_id, 'Authentication Design',
    'Authentication design refers to selecting a technology that meets requirements for confidentiality, integrity, and availability.', 2)
  RETURNING id INTO v_auth_design_id;

  -- Level 3: Authentication Design principles (under Authentication Design)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_auth_design_id, 'Confidentiality (Authentication)',
      'In terms of authentication, is critical, because if account credentials are leaked, threat actors can impersonate the account holder and act on the system with whatever rights they have.', 3),
    (v_subject_id, v_auth_design_id, 'Integrity (Authentication)',
      'It means that the authentication mechanism is reliable and not easy for threat actors to bypass or trick with counterfeit credentials.', 3),
    (v_subject_id, v_auth_design_id, 'Availability (Authentication)',
      'It means that the time taken to authenticate does not impede workflows and is easy enough for users to operate.', 3);

  -- Level 2: Authentication Factor
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_id, 'Authentication Factor',
    'In authentication design, different technologies for implementing authentication, such as knowledge, ownership/token, and biometric/inherence. These are characterized as something you know/have/are.', 2)
  RETURNING id INTO v_auth_factor_id;

  -- Level 3: Authentication Factor types (under Authentication Factor)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_auth_factor_id, 'Something You Know',
      'Something you know is a knowledge factor. It means authentication is based on information that only the authorized user should possess, such as a password, passphrase, or personal identification number (PIN). This could also include answers to security questions or a memorized pattern.', 3),
    (v_subject_id, v_auth_factor_id, 'Something You Have',
      'Something you have is an ownership factor. It means that the account holder possesses something that no one else does, such as a smart card, key fob, or smartphone that can generate or receive a cryptographic token.', 3),
    (v_subject_id, v_auth_factor_id, 'Something You Are',
      'Something you are refers to a biometric or inherence factor. A biometric factor uses either physiological identifiers, such as a fingerprint or facial scan, or behavioral identifiers, such as the way someone moves (gait). The identifiers are scanned and recorded as a template.', 3),
    (v_subject_id, v_auth_factor_id, 'Somewhere You Are',
      'Somewhere you are means the system applies a location-based factor to an authentication decision. Location-based authentication measures some statistics about where you are. This could be a geographic location measured using a device''s location service, or its Internet Protocol (IP) network address.', 3);

  -- Level 2: Password Best Practices
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_auth_id, 'Password Best Practices',
    'Rules to govern secure selection and maintenance of knowledge factor authentication secrets, such as length, complexity, age, and reuse.', 2)
  RETURNING id INTO v_password_practices_id;

  -- Level 3: Password policy elements (under Password Best Practices)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_password_practices_id, 'Password Length',
      'Enforces a minimum length for passwords. There may also be a maximum length.', 3),
    (v_subject_id, v_password_practices_id, 'Password Complexity',
      'Enforces password complexity rules (such as no use of a username within the password and a combination of at least eight uppercase/lowercase alphanumeric and non-alphanumeric characters).', 3),
    (v_subject_id, v_password_practices_id, 'Password Age',
      'Forces the user to select a new password after a set number of days.', 3),
    (v_subject_id, v_password_practices_id, 'Password Reuse and History',
      'Prevents the selection of a password that has been used already. The history attribute sets how many previous passwords are blocked. The minimum age attribute prevents a user from quickly cycling through password changes to revert to a preferred phrase.', 3);

  -----------------------------------------------------------------------------
  -- AUTHORIZATION BRANCH
  -----------------------------------------------------------------------------

  -- Level 2: Access Control Models
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_authz_id, 'Access Control Models',
    'Frameworks that define how access rights and permissions are granted to users, including discretionary, mandatory, role-based, attribute-based, and rule-based models.', 2)
  RETURNING id INTO v_access_control_id;

  -- Level 3: Access Control Model types (under Access Control Models)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_access_control_id, 'Discretionary Access Control (DAC)',
      'An access control model where each resource is protected by an access control list (ACL) managed by the resource''s owner (or owners).', 3),
    (v_subject_id, v_access_control_id, 'Mandatory Access Control (MAC)',
      'An access control model where resources are protected by inflexible, system-defined rules. Resources (objects) and users (subjects) are allocated a clearance level (or label).', 3),
    (v_subject_id, v_access_control_id, 'Role-based Access Control (RBAC)',
      'An access control model where resources are protected by ACLs that are managed by administrators and that provide user permissions based on job functions.', 3),
    (v_subject_id, v_access_control_id, 'Attribute-based Access Control (ABAC)',
      'An access control technique that evaluates a set of attributes that each subject possesses to determine if access should be granted.', 3),
    (v_subject_id, v_access_control_id, 'Rule-based Access Control',
      'A nondiscretionary access control technique that is based on a set of operational rules or restrictions to enforce a least privileges permissions policy.', 3),
    (v_subject_id, v_access_control_id, 'Least Privilege',
      'A basic principle of security stating that something should be allocated the minimum necessary rights, privileges, or information to perform its role.', 3);

  -----------------------------------------------------------------------------
  -- IDENTITY AND ACCESS MANAGEMENT (IAM) BRANCH
  -----------------------------------------------------------------------------

  -- Level 2: Account Management
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_iam_id, 'Account Management',
    'Processes and tools for creating, configuring, monitoring, and controlling user accounts and their privileges, including policies, groups, and privileged access management.', 2)
  RETURNING id INTO v_account_mgmt_id;

  -- Level 3: Account Management components (under Account Management)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_account_mgmt_id, 'Account Policies',
      'A set of rules governing user security information, such as password expiration and uniqueness, which can be set globally.', 3),
    (v_subject_id, v_account_mgmt_id, 'Group Account',
      'A group account is a collection of user accounts that is useful when establishing file permissions and user rights because when many individuals need the same level of access, a group could be established containing all the relevant users.', 3),
    (v_subject_id, v_account_mgmt_id, 'Unique Security Identifier (SID)',
      'The value assigned to an account by Windows and that is used by the operating system to identify that account.', 3),
    (v_subject_id, v_account_mgmt_id, 'Group Policy Objects (GPOs)',
      'On a Windows domain, a way to deploy per-user and per-computer settings such as password policy, account restrictions, firewall status, and so on.', 3),
    (v_subject_id, v_account_mgmt_id, 'Privileged access management (PAM)',
      'Policies, procedures, and support software for managing accounts and credentials with administrative permissions.', 3),
    (v_subject_id, v_account_mgmt_id, 'Secure Administrative Workstation (SAW)',
      'A secure administrative workstation (SAW) is a computer with a very low attack surface running the minimum possible apps.', 3),
    (v_subject_id, v_account_mgmt_id, 'Just-in-time (JIT) Permission',
      'It means that an account''s elevated privileges are not assigned at log-in. Instead, the permissions must be explicitly requested and are only granted for a limited period.', 3),
    (v_subject_id, v_account_mgmt_id, 'M of N Control',
      'Refers to the control which requires multiple people for authentication.', 3);

  -- Level 2: User Account Lifecycle
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_iam_id, 'User Account Lifecycle',
    'The complete process of managing user accounts from creation (provisioning) through active use to removal (deprovisioning), including identity proofing, credential issuance, and access revocation.', 2)
  RETURNING id INTO v_account_lifecycle_id;

  -- Level 3: User Account Provisioning (branch under User Account Lifecycle)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_account_lifecycle_id, 'User Account Provisioning',
    'The process of deploying an account, host, or application to a target production environment. This involves proving the identity or integrity of the resource, and issuing it with credentials and access permissions.', 3)
  RETURNING id INTO v_provisioning_id;

  -- Level 4: Provisioning steps (under User Account Provisioning)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_provisioning_id, 'Identity Proofing',
      'It verifies that the person is who they say they are by checking official documents and records. Circumstances might also demand a background check, which verifies current and previous addresses, education, or previous employment and whether the person has a criminal record or credit issues.', 4),
    (v_subject_id, v_provisioning_id, 'Issuing Credentials',
      'It allows the user to select a password known only to them and/or enroll them with biometric or token-based authenticators.', 4),
    (v_subject_id, v_provisioning_id, 'Issuing Hardware and Software Assets',
      'The user will need, typically a computer and/or smartphone and possibly local copies of licensed software apps. Employees need sufficient resources to do their job. If their resources are inadequate they might try to obtain hardware and software directly (shadow IT).', 4),
    (v_subject_id, v_provisioning_id, 'Teaching Policy Awareness',
      'By scheduling training and providing access to learning resources so that the employee or contractor is aware of security policies and risks. They must also be aware of policies for personal use of any IT assets issued to them.', 4),
    (v_subject_id, v_provisioning_id, 'Creating Permissions Assignment',
      'By identifying the work roles that the account must support and configuring the appropriate rights using a role-based, mandatory, or attribute-based access control model. If the account is granted privileged access, it should be tagged for close monitoring.', 4);

  -- Level 3: User Account Deprovisioning (under User Account Lifecycle)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_account_lifecycle_id, 'User Account Deprovisioning',
      'The process of removing an account, host, or application from the production environment. This requires revoking any privileged access that had been assigned to the object.', 3);

  -- Level 2: Account Restrictions
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_iam_id, 'Account Restrictions',
    'Policies and controls that limit when, where, and how user accounts can be accessed, including location-based, time-based, and zero standing privilege restrictions.', 2)
  RETURNING id INTO v_account_restrictions_id;

  -- Level 3: Account Restriction types (under Account Restrictions)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_account_restrictions_id, 'Geolocation',
      'The identification or estimation of the physical location of an object, such as a radar source, mobile phone, or Internet-connected computing device. IP address can be associated with a map location to varying degrees of accuracy based on information published by the registrant, including name, country, region, and city.', 3),
    (v_subject_id, v_account_restrictions_id, 'Location services',
      'Methods used by the OS to calculate the device''s geographical position. A device with a global positioning system (GPS) sensor can report a highly accurate location when outdoors. Location services can also triangulate to cell towers, Wi-Fi hotspots, and Bluetooth signals where GPS is not supported.', 3),
    (v_subject_id, v_account_restrictions_id, 'Time-of-day Restrictions',
      'This policy establishes authorized login hours for an account. Policies or configuration settings that limit a user''s access to resources.', 3),
    (v_subject_id, v_account_restrictions_id, 'Duration-based Login Policy',
      'It establishes the maximum amount of time an account may be logged in for.', 3),
    (v_subject_id, v_account_restrictions_id, 'Impossible Travel Time / Risky Login Policy',
      'It tracks the location of login events over time. If these do not meet a threshold, the account will be disabled. For example, a user logs in to an account from a device in New York City. A couple of hours later, a login attempt is made from Los Angeles, but is refused and an alert is raised because it is not feasible for the user to be in both locations.', 3),
    (v_subject_id, v_account_restrictions_id, 'Temporary Permissions Policy',
      'It removes an account from a security role or group after a defined period.', 3);

  -- Level 3: Zero Standing Privileges (ZSP) (branch under Account Restrictions)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, v_account_restrictions_id, 'Zero Standing Privileges (ZSP)',
    'Permissions must be explicitly requested and are only granted for a limited period.', 3)
  RETURNING id INTO v_zsp_id;

  -- Level 4: ZSP methods (under Zero Standing Privileges)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_zsp_id, 'Temporary Elevation',
      'Means that the account gains administrative rights for a limited period. The User Account Control (UAC) feature of Windows and the sudo command in Linux use this concept.', 4),
    (v_subject_id, v_zsp_id, 'Password Vaulting/Brokering',
      'Means the privileged account must be "checked out" from a repository and is made available for a limited amount of time. The administrator must log a justification for using the privileges. Approval of the request could be automated via system-enforced policies or require manual intervention, providing a measure of M of N control.', 4),
    (v_subject_id, v_zsp_id, 'Ephemeral Credentials',
      'Means the system generates or enables an account to use to perform the administrative task and then destroys or disables it once the task has been performed. Temporary or ephemeral membership of security groups or roles can serve a similar purpose.', 4);

  -----------------------------------------------------------------------------
  -- FEDERATION (New Level 1 trunk)
  -----------------------------------------------------------------------------

  -- Level 1: Federation
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level)
  VALUES (v_subject_id, NULL, 'Federation',
    'A process that provides a shared login capability across multiple systems and enterprises. It essentially connects the identity management services of multiple systems.', 1)
  RETURNING id INTO v_federation_id;

  -- Level 2: Federation components (under Federation)
  INSERT INTO topics (subject_id, parent_topic_id, name, description, hierarchy_level) VALUES
    (v_subject_id, v_federation_id, 'Identity Provider (IdP)',
      'In a federated network, the service that holds the user account and performs authentication.', 2),
    (v_subject_id, v_federation_id, 'Security Assertion Markup Language (SAML)',
      'An XML-based data format used to exchange authentication information between a client and a service.', 2),
    (v_subject_id, v_federation_id, 'Simple Object Access Protocol (SOAP)',
      'An XML-based web services protocol that is used to exchange messages.', 2),
    (v_subject_id, v_federation_id, 'Representational State Transfer (REST)',
      'A standardized, stateless architectural style used by web applications for communication and integration.', 2),
    (v_subject_id, v_federation_id, 'Open Authorization (OAuth)',
      'A standard for federated identity management, allowing resource servers or consumer sites to work with user accounts created and managed on a separate identity provider. OAuth uses the JavaScript Object Notation (JSON) Web Token (JWT) format for claims data.', 2);

END $$;
